"""Generate, refine, and evaluate answers with Google's Gemini models.

This module refactors the original Colab experiment into reusable functions and
a small command-line application. Set ``GEMINI_API_KEY`` before running it.
"""

from __future__ import annotations

import argparse
import json
import os
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

from datasets import load_dataset
from google import genai
from tqdm import tqdm

FLASH_MODEL = "gemini-2.5-flash"
PRO_MODEL = "gemini-2.5-pro"
DEFAULT_TEMPERATURE = 0.2
DEFAULT_REFINEMENT_ROUNDS = 1
DEFAULT_DATASET_NAME = "databricks/databricks-dolly-15k"
DEFAULT_SAMPLE_COUNT = 100
DEFAULT_START_INDEX = 20
DEFAULT_SPECIAL_INDEX = 18

JsonRecord = dict[str, Any]


class GeminiAnswerService:
    """Generate, critique, refine, and judge answers with Gemini."""

    def __init__(self, api_key: str | None = None) -> None:
        """Initialize the Gemini client using an argument or environment key."""
        resolved_api_key = api_key or os.getenv("GEMINI_API_KEY")
        if not resolved_api_key:
            raise ValueError(
                "A Gemini API key is required. Set GEMINI_API_KEY or pass "
                "api_key explicitly."
            )
        self.client = genai.Client(api_key=resolved_api_key)

    def generate(
        self,
        prompt: str,
        model: str = FLASH_MODEL,
        temperature: float = DEFAULT_TEMPERATURE,
    ) -> str:
        """Return text generated by Gemini for a prompt."""
        response = self.client.models.generate_content(
            model=model,
            contents=prompt,
            config={"temperature": temperature},
        )
        if not response.text:
            raise RuntimeError("Gemini returned an empty response.")
        return response.text

    def create_baseline(self, instruction: str, context: str) -> str:
        """Create an initial answer for an instruction and optional context."""
        prompt = f"""
You are a helpful and intelligent assistant.

Your task is to answer the instruction as clearly and accurately as possible.

Instruction:
{instruction}

Context:
{context}

Note:
If the context is empty or not useful, rely only on your general knowledge.

Provide a complete and well-structured answer.
"""
        return self.generate(prompt, model=FLASH_MODEL)

    def critique(self, instruction: str, context: str, answer: str) -> str:
        """Identify quality issues and missing information in an answer."""
        prompt = f"""
You are an expert evaluator of answer quality.

Evaluate the given answer for:
- completeness
- clarity
- structure
- usefulness
- missing key points from the instruction or context

Instruction:
{instruction}

Context:
{context}

Note:
If the context is empty or not useful, rely only on the instruction and general knowledge.

Answer:
{answer}

Return:
1. Issues found
2. Missing information
"""
        return self.generate(prompt, model=FLASH_MODEL)

    def refine(
        self,
        instruction: str,
        context: str,
        answer: str,
        feedback: str,
    ) -> str:
        """Improve an answer using evaluator feedback."""
        prompt = f"""
You are improving an existing answer.

Rules:
- Fix all issues mentioned in feedback
- Improve clarity, structure, and completeness
- Preserve correct information
- Do NOT add irrelevant content
- Return ONLY the improved answer

Instruction:
{instruction}

Context:
{context}

Note:
If context is empty or not useful, rely only on the instruction.

Original Answer:
{answer}

Feedback:
{feedback}

Improved Answer:
"""
        return self.generate(prompt, model=FLASH_MODEL)

    def self_refine(
        self,
        instruction: str,
        context: str,
        rounds: int = DEFAULT_REFINEMENT_ROUNDS,
    ) -> tuple[str, str]:
        """Return the baseline and refined answers using notebook semantics."""
        for _ in range(rounds):
            original_answer = self.create_baseline(instruction, context)
            refined_answer = original_answer
            feedback = self.critique(instruction, context, refined_answer)
            refined_answer = self.refine(
                instruction, context, refined_answer, feedback
            )
        return original_answer, refined_answer

    def score_answer(
        self,
        question: str,
        context: str,
        ground_truth: str,
        answer: str,
    ) -> int:
        """Score a candidate answer from 1 to 10 using Gemini as evaluator."""
        prompt = f"""
You are an expert QA evaluator.

Evaluate the candidate answer and assign a single overall score from 1 to 10.

Evaluation criteria:
1. Correctness with respect to the ground truth (MOST IMPORTANT)
2. Completeness and clarity
3. Whether the answer is supported by the provided context
4. Penalize hallucinated or unsupported facts

QUESTION:
{question}

CONTEXT:
{context}

GROUND TRUTH:
{ground_truth}

CANDIDATE ANSWER:
{answer}

Return ONLY the numeric score (an integer from 1 to 10).
"""
        score = self.generate(prompt, model=PRO_MODEL, temperature=0)
        return int(score.strip())

    def compare_answers(
        self,
        question: str,
        context: str,
        expected_answer: str,
        answer_a: str,
        answer_b: str,
    ) -> str:
        """Choose between two answers using the notebook's first pairwise judge."""
        prompt = f"""
You are a strict QA evaluator.

Your job is to choose which answer is better.

You must prioritize:
1. Correctness with respect to the question, context and expected answer
2. Completeness and clarity (does it cover all key points in ground truth)
3. Whether the answer is supported by the provided context
4. Penalize hallucinated or unsupported facts


QUESTION:
{question}

CONTEXT:
{context}

EXPECTED ANSWER:
{expected_answer}

ANSWER A:
{answer_a}

ANSWER B:
{answer_b}

Return ONLY one letter:
A or B
"""
        return self.generate(prompt, model=PRO_MODEL, temperature=0).strip()

    def judge(self, sample: Mapping[str, Any]) -> str:
        """Choose the better answer using the original LLM-judge criteria."""
        prompt = f"""
You are a strict QA evaluator.

Your job is to choose which answer is better.

You must prioritize:
1. Correctness against the ground truth (MOST IMPORTANT)
2. Completeness (does it cover all key points in ground truth)
3. Penalize hallucinations (unsupported or incorrect facts)

Ignore:
- writing style
- verbosity
- formatting differences

QUESTION:
{sample['question']}

GROUND TRUTH:
{sample['ground_truth']}

ANSWER A (Baseline):
{sample['baseline']}

ANSWER B (Refined):
{sample['refined']}

Return ONLY one word:
A or B
"""
        return self.generate(prompt, model=PRO_MODEL, temperature=0).strip()


def generate_results(
    service: GeminiAnswerService,
    records: Iterable[Mapping[str, Any]],
    rounds: int = DEFAULT_REFINEMENT_ROUNDS,
) -> list[JsonRecord]:
    """Generate baseline and refined answers for dataset records."""
    results = []
    for record in tqdm(records, desc="Refining answers"):
        question = str(record["instruction"])
        context = str(record.get("context", ""))
        original, refined = service.self_refine(question, context, rounds)
        results.append(
            {
                "question": question,
                "context": context,
                "answer": str(record["response"]),
                "original answer": original,
                "refined_answer": refined,
            }
        )
    return results


def read_json_lines(path: Path) -> list[JsonRecord]:
    """Read JSON objects from a JSON Lines file."""
    records = []
    try:
        with path.open(encoding="utf-8") as input_file:
            for line_number, line in enumerate(input_file, start=1):
                if not line.strip():
                    continue
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError as error:
                    raise ValueError(
                        f"Invalid JSON in {path} on line {line_number}."
                    ) from error
    except OSError as error:
        raise OSError(f"Unable to read {path}: {error}") from error
    return records


def write_json_lines(path: Path, records: Iterable[Mapping[str, Any]]) -> None:
    """Write mappings to a UTF-8 JSON Lines file."""
    try:
        with path.open("w", encoding="utf-8") as output_file:
            for record in records:
                output_file.write(json.dumps(record, ensure_ascii=False) + "\n")
    except OSError as error:
        raise OSError(f"Unable to write {path}: {error}") from error


def changed_results(records: Iterable[JsonRecord]) -> list[JsonRecord]:
    """Return records whose refined answer differs from the baseline."""
    return [
        record
        for record in records
        if record["original answer"] != record["refined_answer"]
    ]


def format_predictions(
    records: Sequence[Mapping[str, Any]], answer_key: str
) -> list[JsonRecord]:
    """Convert records to the prediction format required by SQuAD metrics."""
    return [
        {"id": str(index), "prediction_text": record[answer_key]}
        for index, record in enumerate(records)
    ]


def format_references(records: Sequence[Mapping[str, Any]]) -> list[JsonRecord]:
    """Convert ground truths to the reference format required by SQuAD."""
    return [
        {
            "id": str(index),
            "answers": {"text": [record["ground_truth"]], "answer_start": [0]},
        }
        for index, record in enumerate(records)
    ]


def compute_squad_scores(
    records: Sequence[Mapping[str, Any]], answer_key: str
) -> Mapping[str, float]:
    """Compute exact-match and F1 SQuAD scores for one answer field."""
    import evaluate

    metric = evaluate.load("squad")
    return metric.compute(
        predictions=format_predictions(records, answer_key),
        references=format_references(records),
    )


def load_default_samples() -> list[Mapping[str, Any]]:
    """Load the same Dolly samples selected by the original notebook."""
    dataset = load_dataset(DEFAULT_DATASET_NAME)["train"].select(
        range(DEFAULT_SAMPLE_COUNT)
    )
    samples = list(dataset.select(range(DEFAULT_START_INDEX, DEFAULT_SAMPLE_COUNT)))
    samples.append(dataset[DEFAULT_SPECIAL_INDEX])
    return samples


def build_parser() -> argparse.ArgumentParser:
    """Build the application's command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    generate_parser = subparsers.add_parser(
        "generate", help="Generate and refine answers from Dolly samples."
    )
    generate_parser.add_argument(
        "--output", type=Path, default=Path("results.json")
    )
    generate_parser.add_argument(
        "--changed-output", type=Path, default=Path("temp_results.json")
    )
    generate_parser.add_argument(
        "--rounds", type=int, default=DEFAULT_REFINEMENT_ROUNDS
    )

    evaluate_parser = subparsers.add_parser(
        "evaluate", help="Compute SQuAD metrics for saved results."
    )
    evaluate_parser.add_argument("input", type=Path)
    return parser


def main() -> None:
    """Run the selected command-line workflow."""
    arguments = build_parser().parse_args()
    if arguments.command == "generate":
        service = GeminiAnswerService()
        results = generate_results(service, load_default_samples(), arguments.rounds)
        write_json_lines(arguments.output, results)
        write_json_lines(arguments.changed_output, changed_results(results))
        print(f"Saved {len(results)} results to {arguments.output}.")
        return

    records = read_json_lines(arguments.input)
    print("BASELINE:", compute_squad_scores(records, "baseline"))
    print("REFINED:", compute_squad_scores(records, "refined"))


if __name__ == "__main__":
    main()
